export const mods = [
  "Arena",
  "COD",
  "Combat",
  "Surf",
  "CSDM",
  "Deathrun",
  "DM Lite",
  "Extreme",
  "Human vs Bots",
  "Jailbreak",
  "MIX",
  "Multimod",
  "Paintball",
  "Pistols",
  "Pub",
  "Retake",
  "RPG",
  "Stickers",
  "WCS",
  "[AIM] АИМ",
  "[AWP] АВП",
  "[BHOP] BunnyHop",
  "[CS] Спасение заложников",
  "[DE] С бомбой",
  "[DM] DeathMatch",
  "[FFA] Free for all",
  "[FY] Frag Yard",
  "[GG] ГанГейм",
  "[HNS] Hide and Seek",
  "[HS] HeadShot",
  "[JAIL] Тюрьма",
  "[KZ/Jump] Kreedz Climbing Mod",
  "[MG] MiniGame",
  "[War3FT] Варкрафт",
  "[ZM] Zombie Plague",
  "[ZM] Зомби Мод",
  "Классические",
  "Паблик",
];
