export const mods = [
  "Arena",
  "COD",
  "Combat",
  "Surf",
  "CSDM",
  "Deathrun",
  "DM Lite",
  "Extreme",
  "Human vs Bots",
  "Jailbreak",
  "MIX",
  "Multimod",
  "Paintball",
  "Pistols",
  "Pub",
  "Retake",
  "RPG",
  "Stickers",
  "WCS",
  "[AIM] АИМ",
  "[AWP] АВП",
  "[BHOP] BunnyHop",
  "[CS] Спасение заложников",
  "[DE] С бомбой",
  "[DM] DeathMatch",
  "[FFA] Free for all",
  "[FY] Frag Yard",
  "[GG] ГанГейм",
  "[HNS] Hide and Seek",
  "[HS] HeadShot",
  "[JAIL] Тюрьма",
  "[KZ/Jump] Kreedz Climbing Mod",
  "[MG] MiniGame",
  "[War3FT] Варкрафт",
  "[ZM] Zombie Plague",
  "[ZM] Зомби Мод",
  "Классические",
  "Паблик",
];

export const map_names = [
  // Официальные карты
  "de_dust2",
  "de_mirage",
  "de_inferno",
  "de_nuke",
  "de_vertigo",
  "de_cache",
  "de_dust",
  "de_shortdust",
  "de_ancient",
  "de_anubis",
  "de_overpass",
  "de_train",

  // Hostage карты
  "cs_office",
  "cs_italy",
  "cs_2",
  "cs_agency",

  // Danger Zone
  "dz_arctic",

  // Кастомные AWP карты
  "awp_lego_2",
  "awp_lego_anime_ap3",
  "awp_india",
  "awp_japan",
  "awp_back&yellow",

  // Другие популярные карты
  "poolday",
  "de_safehouse",
  "de_calavera",
  "de_eldorado",
  "de_westwood",
];
