import "../../styles/global.scss";
import ReduxProvider from "@/Components/ReduxProvider/ReduxProvider";
import ToastProvider from "@/Components/ToastContainer/ToastProvider";
import { Geist, Geist_Mono } from "next/font/google";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <main className="container" id="main-content">
            {children}
          </main>
        </ReduxProvider>
        <ToastProvider />
      </body>
    </html>
  );
}
