import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/global.scss";
import ReduxProvider from "@/Components/ReduxProvider/ReduxProvider";
import ToastProvider from "@/Components/ToastContainer/ToastProvider";
import Header from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ReduxProvider>
          <Header />
          <main className="container">{children}</main>
          <Footer />
        </ReduxProvider>
        <ToastProvider />
      </body>
    </html>
  );
}
